remote_theme: pmarsceill/just-the-docs

title: "Harry's Journal"
description: "A collection of my journal entries"
search_enabled: true

nav:
  - title: "Home"
    url: /
  - title: "What is ConfigureServices?"
    url: /docs/WhatIsConfigureServices/
  - title: "What is dotnet task?"
    url: /docs/WhatIsDotnetTask/
