remote_theme: pmarsceill/just-the-docs

title: "Harry's Journal"
description: "A collection of my journal entries"
search_enabled: true

nav:
  - title: "Home"
    url: /
  - title: "What is ConfigureServices? (2024.08.31)"
    url: /docs/2024.08.31-WhatIsConfigureServices/
  - title: "What is dotnet task? (2024.08.28)"
    url: /docs/2024.08.28-WhatIsDotnetTask/
